"""adicionar itens no Pedido

Revision ID: 7ba763b6ffbd
Revises: 5d2ed69a9d72
Create Date: 2025-08-01 14:57:15.990360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba763b6ffbd'
down_revision: Union[str, Sequence[str], None] = '5d2ed69a9d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
